// desktop_pet.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: desktop_pet.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 桌面宠物消息ID
type DesktopPetMessageId int32

const (
	// 基础消息ID范围
	DesktopPetMessageId_DESKTOP_PET_BASE DesktopPetMessageId = 0
	// 认证相关
	DesktopPetMessageId_DESKTOP_PET_AUTH_REQUEST  DesktopPetMessageId = 1001
	DesktopPetMessageId_DESKTOP_PET_AUTH_RESPONSE DesktopPetMessageId = 1002
	// 商城相关
	DesktopPetMessageId_GET_MARKET_ITEMS_REQUEST  DesktopPetMessageId = 1003
	DesktopPetMessageId_GET_MARKET_ITEMS_RESPONSE DesktopPetMessageId = 1004
	// 背包相关
	DesktopPetMessageId_GET_BACKPACK_ITEMS_REQUEST  DesktopPetMessageId = 1005
	DesktopPetMessageId_GET_BACKPACK_ITEMS_RESPONSE DesktopPetMessageId = 1006
	// 购买相关
	DesktopPetMessageId_PURCHASE_REQUEST  DesktopPetMessageId = 1007
	DesktopPetMessageId_PURCHASE_RESPONSE DesktopPetMessageId = 1008
	// 装备相关
	DesktopPetMessageId_EQUIP_REQUEST  DesktopPetMessageId = 1009
	DesktopPetMessageId_EQUIP_RESPONSE DesktopPetMessageId = 1010
	// 皮肤数据相关
	DesktopPetMessageId_GET_SKIN_DATA_REQUEST  DesktopPetMessageId = 1011
	DesktopPetMessageId_GET_SKIN_DATA_RESPONSE DesktopPetMessageId = 1012
	// 动作同步
	DesktopPetMessageId_PET_ACTION_NOTIFICATION DesktopPetMessageId = 1013
	DesktopPetMessageId_PET_CHAT_NOTIFICATION   DesktopPetMessageId = 1014
)

// Enum value maps for DesktopPetMessageId.
var (
	DesktopPetMessageId_name = map[int32]string{
		0:    "DESKTOP_PET_BASE",
		1001: "DESKTOP_PET_AUTH_REQUEST",
		1002: "DESKTOP_PET_AUTH_RESPONSE",
		1003: "GET_MARKET_ITEMS_REQUEST",
		1004: "GET_MARKET_ITEMS_RESPONSE",
		1005: "GET_BACKPACK_ITEMS_REQUEST",
		1006: "GET_BACKPACK_ITEMS_RESPONSE",
		1007: "PURCHASE_REQUEST",
		1008: "PURCHASE_RESPONSE",
		1009: "EQUIP_REQUEST",
		1010: "EQUIP_RESPONSE",
		1011: "GET_SKIN_DATA_REQUEST",
		1012: "GET_SKIN_DATA_RESPONSE",
		1013: "PET_ACTION_NOTIFICATION",
		1014: "PET_CHAT_NOTIFICATION",
	}
	DesktopPetMessageId_value = map[string]int32{
		"DESKTOP_PET_BASE":            0,
		"DESKTOP_PET_AUTH_REQUEST":    1001,
		"DESKTOP_PET_AUTH_RESPONSE":   1002,
		"GET_MARKET_ITEMS_REQUEST":    1003,
		"GET_MARKET_ITEMS_RESPONSE":   1004,
		"GET_BACKPACK_ITEMS_REQUEST":  1005,
		"GET_BACKPACK_ITEMS_RESPONSE": 1006,
		"PURCHASE_REQUEST":            1007,
		"PURCHASE_RESPONSE":           1008,
		"EQUIP_REQUEST":               1009,
		"EQUIP_RESPONSE":              1010,
		"GET_SKIN_DATA_REQUEST":       1011,
		"GET_SKIN_DATA_RESPONSE":      1012,
		"PET_ACTION_NOTIFICATION":     1013,
		"PET_CHAT_NOTIFICATION":       1014,
	}
)

func (x DesktopPetMessageId) Enum() *DesktopPetMessageId {
	p := new(DesktopPetMessageId)
	*p = x
	return p
}

func (x DesktopPetMessageId) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DesktopPetMessageId) Descriptor() protoreflect.EnumDescriptor {
	return file_desktop_pet_proto_enumTypes[0].Descriptor()
}

func (DesktopPetMessageId) Type() protoreflect.EnumType {
	return &file_desktop_pet_proto_enumTypes[0]
}

func (x DesktopPetMessageId) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DesktopPetMessageId.Descriptor instead.
func (DesktopPetMessageId) EnumDescriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{0}
}

// 皮肤信息
type SkinInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name        string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description string `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price       int32  `protobuf:"varint,4,opt,name=price,proto3" json:"price,omitempty"`
	ImageUrl    string `protobuf:"bytes,5,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	Rarity      string `protobuf:"bytes,6,opt,name=rarity,proto3" json:"rarity,omitempty"`      // 稀有度
	Owned       bool   `protobuf:"varint,7,opt,name=owned,proto3" json:"owned,omitempty"`       // 是否已拥有
	Equipped    bool   `protobuf:"varint,8,opt,name=equipped,proto3" json:"equipped,omitempty"` // 是否已装备
}

func (x *SkinInfo) Reset() {
	*x = SkinInfo{}
	mi := &file_desktop_pet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinInfo) ProtoMessage() {}

func (x *SkinInfo) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinInfo.ProtoReflect.Descriptor instead.
func (*SkinInfo) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{0}
}

func (x *SkinInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SkinInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SkinInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *SkinInfo) GetPrice() int32 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SkinInfo) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

func (x *SkinInfo) GetRarity() string {
	if x != nil {
		return x.Rarity
	}
	return ""
}

func (x *SkinInfo) GetOwned() bool {
	if x != nil {
		return x.Owned
	}
	return false
}

func (x *SkinInfo) GetEquipped() bool {
	if x != nil {
		return x.Equipped
	}
	return false
}

// 商城物品列表
type MarketItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   ErrorCode   `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
	Items []*SkinInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *MarketItemsResponse) Reset() {
	*x = MarketItemsResponse{}
	mi := &file_desktop_pet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarketItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarketItemsResponse) ProtoMessage() {}

func (x *MarketItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarketItemsResponse.ProtoReflect.Descriptor instead.
func (*MarketItemsResponse) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{1}
}

func (x *MarketItemsResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

func (x *MarketItemsResponse) GetItems() []*SkinInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// 背包物品列表
type BackpackItemsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret   ErrorCode   `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
	Items []*SkinInfo `protobuf:"bytes,2,rep,name=items,proto3" json:"items,omitempty"`
}

func (x *BackpackItemsResponse) Reset() {
	*x = BackpackItemsResponse{}
	mi := &file_desktop_pet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackpackItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackpackItemsResponse) ProtoMessage() {}

func (x *BackpackItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackpackItemsResponse.ProtoReflect.Descriptor instead.
func (*BackpackItemsResponse) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{2}
}

func (x *BackpackItemsResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

func (x *BackpackItemsResponse) GetItems() []*SkinInfo {
	if x != nil {
		return x.Items
	}
	return nil
}

// 购买请求
type PurchaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId   string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
	ItemType string `protobuf:"bytes,2,opt,name=item_type,json=itemType,proto3" json:"item_type,omitempty"` // skin, decoration, etc.
}

func (x *PurchaseRequest) Reset() {
	*x = PurchaseRequest{}
	mi := &file_desktop_pet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseRequest) ProtoMessage() {}

func (x *PurchaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseRequest.ProtoReflect.Descriptor instead.
func (*PurchaseRequest) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{3}
}

func (x *PurchaseRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

func (x *PurchaseRequest) GetItemType() string {
	if x != nil {
		return x.ItemType
	}
	return ""
}

// 购买响应
type PurchaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
	ItemId string    `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *PurchaseResponse) Reset() {
	*x = PurchaseResponse{}
	mi := &file_desktop_pet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PurchaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PurchaseResponse) ProtoMessage() {}

func (x *PurchaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PurchaseResponse.ProtoReflect.Descriptor instead.
func (*PurchaseResponse) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{4}
}

func (x *PurchaseResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

func (x *PurchaseResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// 装备请求
type EquipRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId string `protobuf:"bytes,1,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *EquipRequest) Reset() {
	*x = EquipRequest{}
	mi := &file_desktop_pet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipRequest) ProtoMessage() {}

func (x *EquipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipRequest.ProtoReflect.Descriptor instead.
func (*EquipRequest) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{5}
}

func (x *EquipRequest) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// 装备响应
type EquipResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret    ErrorCode `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
	ItemId string    `protobuf:"bytes,2,opt,name=item_id,json=itemId,proto3" json:"item_id,omitempty"`
}

func (x *EquipResponse) Reset() {
	*x = EquipResponse{}
	mi := &file_desktop_pet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EquipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipResponse) ProtoMessage() {}

func (x *EquipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipResponse.ProtoReflect.Descriptor instead.
func (*EquipResponse) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{6}
}

func (x *EquipResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

func (x *EquipResponse) GetItemId() string {
	if x != nil {
		return x.ItemId
	}
	return ""
}

// 皮肤数据请求
type SkinDataRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SkinId string `protobuf:"bytes,1,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
}

func (x *SkinDataRequest) Reset() {
	*x = SkinDataRequest{}
	mi := &file_desktop_pet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinDataRequest) ProtoMessage() {}

func (x *SkinDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinDataRequest.ProtoReflect.Descriptor instead.
func (*SkinDataRequest) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{7}
}

func (x *SkinDataRequest) GetSkinId() string {
	if x != nil {
		return x.SkinId
	}
	return ""
}

// 皮肤数据响应
type SkinDataResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret      ErrorCode `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
	SkinId   string    `protobuf:"bytes,2,opt,name=skin_id,json=skinId,proto3" json:"skin_id,omitempty"`
	SkinData []byte    `protobuf:"bytes,3,opt,name=skin_data,json=skinData,proto3" json:"skin_data,omitempty"` // 加密的皮肤数据
}

func (x *SkinDataResponse) Reset() {
	*x = SkinDataResponse{}
	mi := &file_desktop_pet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkinDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkinDataResponse) ProtoMessage() {}

func (x *SkinDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkinDataResponse.ProtoReflect.Descriptor instead.
func (*SkinDataResponse) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{8}
}

func (x *SkinDataResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

func (x *SkinDataResponse) GetSkinId() string {
	if x != nil {
		return x.SkinId
	}
	return ""
}

func (x *SkinDataResponse) GetSkinData() []byte {
	if x != nil {
		return x.SkinData
	}
	return nil
}

// 桌面宠物玩家状态
type DesktopPetPlayerState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   uint64  `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerName string  `protobuf:"bytes,2,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	PetSkin    string  `protobuf:"bytes,3,opt,name=pet_skin,json=petSkin,proto3" json:"pet_skin,omitempty"`
	PositionX  float32 `protobuf:"fixed32,4,opt,name=position_x,json=positionX,proto3" json:"position_x,omitempty"`
	PositionY  float32 `protobuf:"fixed32,5,opt,name=position_y,json=positionY,proto3" json:"position_y,omitempty"`
	Action     string  `protobuf:"bytes,6,opt,name=action,proto3" json:"action,omitempty"`
	ChatText   string  `protobuf:"bytes,7,opt,name=chat_text,json=chatText,proto3" json:"chat_text,omitempty"`
}

func (x *DesktopPetPlayerState) Reset() {
	*x = DesktopPetPlayerState{}
	mi := &file_desktop_pet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesktopPetPlayerState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopPetPlayerState) ProtoMessage() {}

func (x *DesktopPetPlayerState) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopPetPlayerState.ProtoReflect.Descriptor instead.
func (*DesktopPetPlayerState) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{9}
}

func (x *DesktopPetPlayerState) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *DesktopPetPlayerState) GetPlayerName() string {
	if x != nil {
		return x.PlayerName
	}
	return ""
}

func (x *DesktopPetPlayerState) GetPetSkin() string {
	if x != nil {
		return x.PetSkin
	}
	return ""
}

func (x *DesktopPetPlayerState) GetPositionX() float32 {
	if x != nil {
		return x.PositionX
	}
	return 0
}

func (x *DesktopPetPlayerState) GetPositionY() float32 {
	if x != nil {
		return x.PositionY
	}
	return 0
}

func (x *DesktopPetPlayerState) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *DesktopPetPlayerState) GetChatText() string {
	if x != nil {
		return x.ChatText
	}
	return ""
}

// 桌面宠物房间状态
type DesktopPetRoomState struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RoomId  string                   `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	Players []*DesktopPetPlayerState `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
}

func (x *DesktopPetRoomState) Reset() {
	*x = DesktopPetRoomState{}
	mi := &file_desktop_pet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesktopPetRoomState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesktopPetRoomState) ProtoMessage() {}

func (x *DesktopPetRoomState) ProtoReflect() protoreflect.Message {
	mi := &file_desktop_pet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesktopPetRoomState.ProtoReflect.Descriptor instead.
func (*DesktopPetRoomState) Descriptor() ([]byte, []int) {
	return file_desktop_pet_proto_rawDescGZIP(), []int{10}
}

func (x *DesktopPetRoomState) GetRoomId() string {
	if x != nil {
		return x.RoomId
	}
	return ""
}

func (x *DesktopPetRoomState) GetPlayers() []*DesktopPetPlayerState {
	if x != nil {
		return x.Players
	}
	return nil
}

var File_desktop_pet_proto protoreflect.FileDescriptor

var file_desktop_pet_proto_rawDesc = []byte{
	0x0a, 0x11, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x65, 0x74, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x65, 0x74,
	0x1a, 0x0a, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xcd, 0x01, 0x0a,
	0x08, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a,
	0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x14, 0x0a, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05,
	0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x6d, 0x61, 0x67, 0x65, 0x55,
	0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77,
	0x6e, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x64,
	0x12, 0x1a, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x70, 0x65, 0x64, 0x22, 0x65, 0x0a, 0x13,
	0x4d, 0x61, 0x72, 0x6b, 0x65, 0x74, 0x49, 0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x5f,
	0x70, 0x65, 0x74, 0x2e, 0x53, 0x6b, 0x69, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74,
	0x65, 0x6d, 0x73, 0x22, 0x67, 0x0a, 0x15, 0x42, 0x61, 0x63, 0x6b, 0x70, 0x61, 0x63, 0x6b, 0x49,
	0x74, 0x65, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65,
	0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12,
	0x2b, 0x0a, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x64, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x65, 0x74, 0x2e, 0x53, 0x6b, 0x69,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x69, 0x74, 0x65, 0x6d, 0x73, 0x22, 0x47, 0x0a, 0x0f,
	0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65,
	0x6d, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4e, 0x0a, 0x10, 0x50, 0x75, 0x72, 0x63, 0x68, 0x61, 0x73,
	0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x17, 0x0a, 0x07,
	0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x27, 0x0a, 0x0c, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x4b,
	0x0a, 0x0d, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x21, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67,
	0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x2a, 0x0a, 0x0f, 0x53,
	0x6b, 0x69, 0x6e, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x22, 0x6b, 0x0a, 0x10, 0x53, 0x6b, 0x69, 0x6e, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x72,
	0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x6b, 0x69, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x73, 0x6b, 0x69, 0x6e, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x6b, 0x69, 0x6e, 0x5f,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x73, 0x6b, 0x69, 0x6e,
	0x44, 0x61, 0x74, 0x61, 0x22, 0xe3, 0x01, 0x0a, 0x15, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f, 0x70,
	0x50, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1b,
	0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x70, 0x65, 0x74, 0x5f, 0x73, 0x6b, 0x69, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x70, 0x65, 0x74, 0x53, 0x6b, 0x69, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x58, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x02, 0x52, 0x09, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x59, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a,
	0x09, 0x63, 0x68, 0x61, 0x74, 0x5f, 0x74, 0x65, 0x78, 0x74, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x63, 0x68, 0x61, 0x74, 0x54, 0x65, 0x78, 0x74, 0x22, 0x6c, 0x0a, 0x13, 0x44, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x50, 0x65, 0x74, 0x52, 0x6f, 0x6f, 0x6d, 0x53, 0x74, 0x61, 0x74,
	0x65, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x6f, 0x6f, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x72, 0x6f, 0x6f, 0x6d, 0x49, 0x64, 0x12, 0x3c, 0x0a, 0x07, 0x70, 0x6c,
	0x61, 0x79, 0x65, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x64, 0x65,
	0x73, 0x6b, 0x74, 0x6f, 0x70, 0x5f, 0x70, 0x65, 0x74, 0x2e, 0x44, 0x65, 0x73, 0x6b, 0x74, 0x6f,
	0x70, 0x50, 0x65, 0x74, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x53, 0x74, 0x61, 0x74, 0x65, 0x52,
	0x07, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x73, 0x2a, 0xb7, 0x03, 0x0a, 0x13, 0x44, 0x65, 0x73,
	0x6b, 0x74, 0x6f, 0x70, 0x50, 0x65, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x10, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50, 0x5f, 0x50, 0x45, 0x54, 0x5f,
	0x42, 0x41, 0x53, 0x45, 0x10, 0x00, 0x12, 0x1d, 0x0a, 0x18, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f,
	0x50, 0x5f, 0x50, 0x45, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0xe9, 0x07, 0x12, 0x1e, 0x0a, 0x19, 0x44, 0x45, 0x53, 0x4b, 0x54, 0x4f, 0x50,
	0x5f, 0x50, 0x45, 0x54, 0x5f, 0x41, 0x55, 0x54, 0x48, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e,
	0x53, 0x45, 0x10, 0xea, 0x07, 0x12, 0x1d, 0x0a, 0x18, 0x47, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x52,
	0x4b, 0x45, 0x54, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53,
	0x54, 0x10, 0xeb, 0x07, 0x12, 0x1e, 0x0a, 0x19, 0x47, 0x45, 0x54, 0x5f, 0x4d, 0x41, 0x52, 0x4b,
	0x45, 0x54, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53,
	0x45, 0x10, 0xec, 0x07, 0x12, 0x1f, 0x0a, 0x1a, 0x47, 0x45, 0x54, 0x5f, 0x42, 0x41, 0x43, 0x4b,
	0x50, 0x41, 0x43, 0x4b, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x53, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45,
	0x53, 0x54, 0x10, 0xed, 0x07, 0x12, 0x20, 0x0a, 0x1b, 0x47, 0x45, 0x54, 0x5f, 0x42, 0x41, 0x43,
	0x4b, 0x50, 0x41, 0x43, 0x4b, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x53, 0x5f, 0x52, 0x45, 0x53, 0x50,
	0x4f, 0x4e, 0x53, 0x45, 0x10, 0xee, 0x07, 0x12, 0x15, 0x0a, 0x10, 0x50, 0x55, 0x52, 0x43, 0x48,
	0x41, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0xef, 0x07, 0x12, 0x16,
	0x0a, 0x11, 0x50, 0x55, 0x52, 0x43, 0x48, 0x41, 0x53, 0x45, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f,
	0x4e, 0x53, 0x45, 0x10, 0xf0, 0x07, 0x12, 0x12, 0x0a, 0x0d, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f,
	0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0xf1, 0x07, 0x12, 0x13, 0x0a, 0x0e, 0x45, 0x51,
	0x55, 0x49, 0x50, 0x5f, 0x52, 0x45, 0x53, 0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0xf2, 0x07, 0x12,
	0x1a, 0x0a, 0x15, 0x47, 0x45, 0x54, 0x5f, 0x53, 0x4b, 0x49, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41,
	0x5f, 0x52, 0x45, 0x51, 0x55, 0x45, 0x53, 0x54, 0x10, 0xf3, 0x07, 0x12, 0x1b, 0x0a, 0x16, 0x47,
	0x45, 0x54, 0x5f, 0x53, 0x4b, 0x49, 0x4e, 0x5f, 0x44, 0x41, 0x54, 0x41, 0x5f, 0x52, 0x45, 0x53,
	0x50, 0x4f, 0x4e, 0x53, 0x45, 0x10, 0xf4, 0x07, 0x12, 0x1c, 0x0a, 0x17, 0x50, 0x45, 0x54, 0x5f,
	0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54,
	0x49, 0x4f, 0x4e, 0x10, 0xf5, 0x07, 0x12, 0x1a, 0x0a, 0x15, 0x50, 0x45, 0x54, 0x5f, 0x43, 0x48,
	0x41, 0x54, 0x5f, 0x4e, 0x4f, 0x54, 0x49, 0x46, 0x49, 0x43, 0x41, 0x54, 0x49, 0x4f, 0x4e, 0x10,
	0xf6, 0x07, 0x42, 0x12, 0x5a, 0x10, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_desktop_pet_proto_rawDescOnce sync.Once
	file_desktop_pet_proto_rawDescData = file_desktop_pet_proto_rawDesc
)

func file_desktop_pet_proto_rawDescGZIP() []byte {
	file_desktop_pet_proto_rawDescOnce.Do(func() {
		file_desktop_pet_proto_rawDescData = protoimpl.X.CompressGZIP(file_desktop_pet_proto_rawDescData)
	})
	return file_desktop_pet_proto_rawDescData
}

var file_desktop_pet_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_desktop_pet_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_desktop_pet_proto_goTypes = []any{
	(DesktopPetMessageId)(0),      // 0: desktop_pet.DesktopPetMessageId
	(*SkinInfo)(nil),              // 1: desktop_pet.SkinInfo
	(*MarketItemsResponse)(nil),   // 2: desktop_pet.MarketItemsResponse
	(*BackpackItemsResponse)(nil), // 3: desktop_pet.BackpackItemsResponse
	(*PurchaseRequest)(nil),       // 4: desktop_pet.PurchaseRequest
	(*PurchaseResponse)(nil),      // 5: desktop_pet.PurchaseResponse
	(*EquipRequest)(nil),          // 6: desktop_pet.EquipRequest
	(*EquipResponse)(nil),         // 7: desktop_pet.EquipResponse
	(*SkinDataRequest)(nil),       // 8: desktop_pet.SkinDataRequest
	(*SkinDataResponse)(nil),      // 9: desktop_pet.SkinDataResponse
	(*DesktopPetPlayerState)(nil), // 10: desktop_pet.DesktopPetPlayerState
	(*DesktopPetRoomState)(nil),   // 11: desktop_pet.DesktopPetRoomState
	(ErrorCode)(0),                // 12: game.ErrorCode
}
var file_desktop_pet_proto_depIdxs = []int32{
	12, // 0: desktop_pet.MarketItemsResponse.ret:type_name -> game.ErrorCode
	1,  // 1: desktop_pet.MarketItemsResponse.items:type_name -> desktop_pet.SkinInfo
	12, // 2: desktop_pet.BackpackItemsResponse.ret:type_name -> game.ErrorCode
	1,  // 3: desktop_pet.BackpackItemsResponse.items:type_name -> desktop_pet.SkinInfo
	12, // 4: desktop_pet.PurchaseResponse.ret:type_name -> game.ErrorCode
	12, // 5: desktop_pet.EquipResponse.ret:type_name -> game.ErrorCode
	12, // 6: desktop_pet.SkinDataResponse.ret:type_name -> game.ErrorCode
	10, // 7: desktop_pet.DesktopPetRoomState.players:type_name -> desktop_pet.DesktopPetPlayerState
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_desktop_pet_proto_init() }
func file_desktop_pet_proto_init() {
	if File_desktop_pet_proto != nil {
		return
	}
	file_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_desktop_pet_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_desktop_pet_proto_goTypes,
		DependencyIndexes: file_desktop_pet_proto_depIdxs,
		EnumInfos:         file_desktop_pet_proto_enumTypes,
		MessageInfos:      file_desktop_pet_proto_msgTypes,
	}.Build()
	File_desktop_pet_proto = out.File
	file_desktop_pet_proto_rawDesc = nil
	file_desktop_pet_proto_goTypes = nil
	file_desktop_pet_proto_depIdxs = nil
}
