// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.0
// source: match.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchService_StartMatch_FullMethodName = "/match.MatchService/StartMatch"
)

// MatchServiceClient is the client API for MatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 匹配服务
type MatchServiceClient interface {
	StartMatch(ctx context.Context, in *SSMatchRequest, opts ...grpc.CallOption) (*SSMatchResponse, error)
}

type matchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchServiceClient(cc grpc.ClientConnInterface) MatchServiceClient {
	return &matchServiceClient{cc}
}

func (c *matchServiceClient) StartMatch(ctx context.Context, in *SSMatchRequest, opts ...grpc.CallOption) (*SSMatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SSMatchResponse)
	err := c.cc.Invoke(ctx, MatchService_StartMatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchServiceServer is the server API for MatchService service.
// All implementations must embed UnimplementedMatchServiceServer
// for forward compatibility.
//
// 匹配服务
type MatchServiceServer interface {
	StartMatch(context.Context, *SSMatchRequest) (*SSMatchResponse, error)
	mustEmbedUnimplementedMatchServiceServer()
}

// UnimplementedMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchServiceServer struct{}

func (UnimplementedMatchServiceServer) StartMatch(context.Context, *SSMatchRequest) (*SSMatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StartMatch not implemented")
}
func (UnimplementedMatchServiceServer) mustEmbedUnimplementedMatchServiceServer() {}
func (UnimplementedMatchServiceServer) testEmbeddedByValue()                      {}

// UnsafeMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchServiceServer will
// result in compilation errors.
type UnsafeMatchServiceServer interface {
	mustEmbedUnimplementedMatchServiceServer()
}

func RegisterMatchServiceServer(s grpc.ServiceRegistrar, srv MatchServiceServer) {
	// If the following call pancis, it indicates UnimplementedMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchService_ServiceDesc, srv)
}

func _MatchService_StartMatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSMatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchServiceServer).StartMatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchService_StartMatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchServiceServer).StartMatch(ctx, req.(*SSMatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchService_ServiceDesc is the grpc.ServiceDesc for MatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match.MatchService",
	HandlerType: (*MatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartMatch",
			Handler:    _MatchService_StartMatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match.proto",
}

const (
	InternalMatchService_OnMatchSuccess_FullMethodName = "/match.InternalMatchService/OnMatchSuccess"
)

// InternalMatchServiceClient is the client API for InternalMatchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 内部服务注册
type InternalMatchServiceClient interface {
	OnMatchSuccess(ctx context.Context, in *SSMatchResultNotify, opts ...grpc.CallOption) (*MatchResult, error)
}

type internalMatchServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewInternalMatchServiceClient(cc grpc.ClientConnInterface) InternalMatchServiceClient {
	return &internalMatchServiceClient{cc}
}

func (c *internalMatchServiceClient) OnMatchSuccess(ctx context.Context, in *SSMatchResultNotify, opts ...grpc.CallOption) (*MatchResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchResult)
	err := c.cc.Invoke(ctx, InternalMatchService_OnMatchSuccess_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// InternalMatchServiceServer is the server API for InternalMatchService service.
// All implementations must embed UnimplementedInternalMatchServiceServer
// for forward compatibility.
//
// 内部服务注册
type InternalMatchServiceServer interface {
	OnMatchSuccess(context.Context, *SSMatchResultNotify) (*MatchResult, error)
	mustEmbedUnimplementedInternalMatchServiceServer()
}

// UnimplementedInternalMatchServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedInternalMatchServiceServer struct{}

func (UnimplementedInternalMatchServiceServer) OnMatchSuccess(context.Context, *SSMatchResultNotify) (*MatchResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OnMatchSuccess not implemented")
}
func (UnimplementedInternalMatchServiceServer) mustEmbedUnimplementedInternalMatchServiceServer() {}
func (UnimplementedInternalMatchServiceServer) testEmbeddedByValue()                              {}

// UnsafeInternalMatchServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to InternalMatchServiceServer will
// result in compilation errors.
type UnsafeInternalMatchServiceServer interface {
	mustEmbedUnimplementedInternalMatchServiceServer()
}

func RegisterInternalMatchServiceServer(s grpc.ServiceRegistrar, srv InternalMatchServiceServer) {
	// If the following call pancis, it indicates UnimplementedInternalMatchServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&InternalMatchService_ServiceDesc, srv)
}

func _InternalMatchService_OnMatchSuccess_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SSMatchResultNotify)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(InternalMatchServiceServer).OnMatchSuccess(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: InternalMatchService_OnMatchSuccess_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(InternalMatchServiceServer).OnMatchSuccess(ctx, req.(*SSMatchResultNotify))
	}
	return interceptor(ctx, in, info, handler)
}

// InternalMatchService_ServiceDesc is the grpc.ServiceDesc for InternalMatchService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var InternalMatchService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "match.InternalMatchService",
	HandlerType: (*InternalMatchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "OnMatchSuccess",
			Handler:    _InternalMatchService_OnMatchSuccess_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "match.proto",
}
