// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.2
// 	protoc        v5.29.0
// source: match_service.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MatchRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId   uint64          `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	PlayerData *PlayerInitData `protobuf:"bytes,2,opt,name=player_data,json=playerData,proto3" json:"player_data,omitempty"` // 玩家初始数据（卡组/位置等）
}

func (x *MatchRpcRequest) Reset() {
	*x = MatchRpcRequest{}
	mi := &file_match_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRpcRequest) ProtoMessage() {}

func (x *MatchRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRpcRequest.ProtoReflect.Descriptor instead.
func (*MatchRpcRequest) Descriptor() ([]byte, []int) {
	return file_match_service_proto_rawDescGZIP(), []int{0}
}

func (x *MatchRpcRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

func (x *MatchRpcRequest) GetPlayerData() *PlayerInitData {
	if x != nil {
		return x.PlayerData
	}
	return nil
}

// 匹配响应
type MatchRpcResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret ErrorCode `protobuf:"varint,1,opt,name=ret,proto3,enum=game.ErrorCode" json:"ret,omitempty"`
}

func (x *MatchRpcResponse) Reset() {
	*x = MatchRpcResponse{}
	mi := &file_match_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchRpcResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchRpcResponse) ProtoMessage() {}

func (x *MatchRpcResponse) ProtoReflect() protoreflect.Message {
	mi := &file_match_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchRpcResponse.ProtoReflect.Descriptor instead.
func (*MatchRpcResponse) Descriptor() ([]byte, []int) {
	return file_match_service_proto_rawDescGZIP(), []int{1}
}

func (x *MatchRpcResponse) GetRet() ErrorCode {
	if x != nil {
		return x.Ret
	}
	return ErrorCode_OK
}

type CancelMatchRpcRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PlayerId uint64 `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
}

func (x *CancelMatchRpcRequest) Reset() {
	*x = CancelMatchRpcRequest{}
	mi := &file_match_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelMatchRpcRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelMatchRpcRequest) ProtoMessage() {}

func (x *CancelMatchRpcRequest) ProtoReflect() protoreflect.Message {
	mi := &file_match_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelMatchRpcRequest.ProtoReflect.Descriptor instead.
func (*CancelMatchRpcRequest) Descriptor() ([]byte, []int) {
	return file_match_service_proto_rawDescGZIP(), []int{2}
}

func (x *CancelMatchRpcRequest) GetPlayerId() uint64 {
	if x != nil {
		return x.PlayerId
	}
	return 0
}

var File_match_service_proto protoreflect.FileDescriptor

var file_match_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x1a, 0x0a, 0x67, 0x61,
	0x6d, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x65, 0x0a, 0x0f, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08,
	0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x12, 0x35, 0x0a, 0x0b, 0x70, 0x6c, 0x61, 0x79,
	0x65, 0x72, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x67, 0x61, 0x6d, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x6e, 0x69, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x0a, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x22,
	0x35, 0x0a, 0x10, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0f, 0x2e, 0x67, 0x61, 0x6d, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6f, 0x64,
	0x65, 0x52, 0x03, 0x72, 0x65, 0x74, 0x22, 0x34, 0x0a, 0x15, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c,
	0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x08, 0x70, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x49, 0x64, 0x32, 0x9c, 0x01, 0x0a,
	0x0f, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x40, 0x0a, 0x0d, 0x53, 0x74, 0x61, 0x72, 0x74, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70,
	0x63, 0x12, 0x16, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52,
	0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x74, 0x63,
	0x68, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x0e, 0x43, 0x61, 0x6e, 0x63, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63,
	0x68, 0x52, 0x70, 0x63, 0x12, 0x1c, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x43, 0x61, 0x6e,
	0x63, 0x65, 0x6c, 0x4d, 0x61, 0x74, 0x63, 0x68, 0x52, 0x70, 0x63, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x6d, 0x61, 0x74, 0x63, 0x68, 0x2e, 0x4d, 0x61, 0x74, 0x63, 0x68,
	0x52, 0x70, 0x63, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x73, 0x72, 0x63, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_match_service_proto_rawDescOnce sync.Once
	file_match_service_proto_rawDescData = file_match_service_proto_rawDesc
)

func file_match_service_proto_rawDescGZIP() []byte {
	file_match_service_proto_rawDescOnce.Do(func() {
		file_match_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_match_service_proto_rawDescData)
	})
	return file_match_service_proto_rawDescData
}

var file_match_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_match_service_proto_goTypes = []any{
	(*MatchRpcRequest)(nil),       // 0: match.MatchRpcRequest
	(*MatchRpcResponse)(nil),      // 1: match.MatchRpcResponse
	(*CancelMatchRpcRequest)(nil), // 2: match.CancelMatchRpcRequest
	(*PlayerInitData)(nil),        // 3: game.PlayerInitData
	(ErrorCode)(0),                // 4: game.ErrorCode
}
var file_match_service_proto_depIdxs = []int32{
	3, // 0: match.MatchRpcRequest.player_data:type_name -> game.PlayerInitData
	4, // 1: match.MatchRpcResponse.ret:type_name -> game.ErrorCode
	0, // 2: match.MatchRpcService.StartMatchRpc:input_type -> match.MatchRpcRequest
	2, // 3: match.MatchRpcService.CancelMatchRpc:input_type -> match.CancelMatchRpcRequest
	1, // 4: match.MatchRpcService.StartMatchRpc:output_type -> match.MatchRpcResponse
	1, // 5: match.MatchRpcService.CancelMatchRpc:output_type -> match.MatchRpcResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_match_service_proto_init() }
func file_match_service_proto_init() {
	if File_match_service_proto != nil {
		return
	}
	file_game_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_match_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_match_service_proto_goTypes,
		DependencyIndexes: file_match_service_proto_depIdxs,
		MessageInfos:      file_match_service_proto_msgTypes,
	}.Build()
	File_match_service_proto = out.File
	file_match_service_proto_rawDesc = nil
	file_match_service_proto_goTypes = nil
	file_match_service_proto_depIdxs = nil
}
