
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


type CfgTbDrawCard struct {
    _dataMap map[int32]*CfgDrawCard
    _dataList []*CfgDrawCard
}

func NewCfgTbDrawCard(_buf []map[string]interface{}) (*CfgTbDrawCard, error) {
    _dataList := make([]*CfgDrawCard, 0, len(_buf))
    dataMap := make(map[int32]*CfgDrawCard)

    for _, _ele_ := range _buf {
        if _v, err2 := NewCfgDrawCard(_ele_); err2 != nil {
            return nil, err2
        } else {
            _dataList = append(_dataList, _v)
            dataMap[_v.RarityLevel] = _v
        }
    }
    return &CfgTbDrawCard{_dataList:_dataList, _dataMap:dataMap}, nil
}

func (table *CfgTbDrawCard) GetDataMap() map[int32]*CfgDrawCard {
    return table._dataMap
}

func (table *CfgTbDrawCard) GetDataList() []*CfgDrawCard {
    return table._dataList
}

func (table *CfgTbDrawCard) Get(key int32) *CfgDrawCard {
    return table._dataMap[key]
}


