
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

package cfg;


import "errors"

type CfgValueRange struct {
    Base int32
    Variance float32
}

const TypeId_CfgValueRange = 711461430

func (*CfgValueRange) GetTypeId() int32 {
    return 711461430
}

func NewCfgValueRange(_buf map[string]interface{}) (_v *CfgValueRange, err error) {
    _v = &CfgValueRange{}
    { var _ok_ bool; var __json_base__ interface{}; if __json_base__, _ok_ = _buf["base"]; !_ok_ || __json_base__ == nil { err = errors.New("base error"); return } else { var __x__ int32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_base__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = int32(_x_) }; _v.Base = __x__ }}
    { var _ok_ bool; var __json_variance__ interface{}; if __json_variance__, _ok_ = _buf["variance"]; !_ok_ || __json_variance__ == nil { err = errors.New("variance error"); return } else { var __x__ float32;  { var _ok_ bool; var _x_ float64; if _x_, _ok_ = __json_variance__.(float64); !_ok_ { err = errors.New("__x__ error"); return }; __x__ = float32(_x_) }; _v.Variance = __x__ }}
    return
}

